import { NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt: prompt,
      n: 1,
      size: "1024x1024",
    });

    const imageUrl = response.data?.[0]?.url;

    if (!imageUrl) {
      throw new Error("No image generated by OpenAI.");
    }

    return NextResponse.json({ imageUrl });
  } catch (error: any) {
    console.error("OpenAI Generation Error:", error.message || error);
    return NextResponse.json({ error: error.message || "Failed to generate image" }, { status: 500 });
  }
}
